name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image for ECommerce.WebAPI
      run: docker build ./ECommerce.WebAPI --file ./ECommerce.WebAPI/Dockerfile --tag my-image-name:$(date +%s)
